#!/bin/sh
# castoro-s3-adapter start/stop script.
# chkconfig: - 85 15
# description: castoro-s3-adapter start/stop script.
. /etc/rc.d/init.d/functions

prog=castoro-s3-adapterd

dir=`dirname \`which ruby\``
base=${dir}/castoro-s3-adapter

cnf=/etc/castoro/s3-adapter.conf
pid=/var/castoro/s3-adapter.pid
log=/var/castoro/s3-adapter.log
env=default

start() {
  echo $"Start Castoro-S3Adapter ..."
  $base start -c $cnf -p $pid -l $log -e $env -d
}

stop() {
  echo $"Stop Castoro-S3Adapter ..."
  $base stop -p $pid
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status -p $pid $prog
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status}"
esac

